os: linux
dist: bionic
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - sudo apt-get install cppcheck

script:
  # Check versions
  - cppcheck --version

  #cppcheck flight software fsw/cfe-core/src and modules
  - cppcheck --force --inline-suppr --std=c99 --language=c --error-exitcode=1 --enable=warning,performance,portability,style --suppress=variableScope --inconclusive fsw/cfe-core/src modules 2>cppcheck_flight_cfe.txt
  - |
    if [[ -s cppcheck_flight_cfe.txt ]]; then
      echo "You must fix cppcheck errors before submitting a pull request"
      echo ""
      cat cppcheck_flight_cfe.txt
      exit -1
    fi

